// lib/gomi/registry.ts — 生成物。scripts/generate-muni-registry.mjs で再生成すること。
// JSON importゼロ（sitemap.ts / 親ページのリンク索引から安全にimportできる）。
// core.ts の 97import 壁を回避するための静的レジストリ。
export type MuniRegistryEntry = {
  slug: string;
  file: string;
  name: string;
  city: string;
  areaCount: number;
};

export const MUNI_REGISTRY: MuniRegistryEntry[] = [
  { slug: "meguro", file: "meguro-schedule.json", name: "目黒区", city: "東京23区", areaCount: 88 },
  { slug: "shinagawa", file: "shinagawa-schedule.json", name: "品川区", city: "東京23区", areaCount: 137 },
  { slug: "taito", file: "taito-schedule.json", name: "台東区", city: "東京23区", areaCount: 108 },
  { slug: "koto", file: "koto-schedule.json", name: "江東区", city: "東京23区", areaCount: 58 },
  { slug: "bunkyo", file: "bunkyo-schedule.json", name: "文京区", city: "東京23区", areaCount: 33 },
  { slug: "chuo", file: "chuo-schedule.json", name: "中央区", city: "東京23区", areaCount: 56 },
  { slug: "ota", file: "ota-schedule.json", name: "大田区", city: "東京23区", areaCount: 87 },
  { slug: "setagaya", file: "setagaya-schedule.json", name: "世田谷区", city: "東京23区", areaCount: 277 },
  { slug: "nerima", file: "nerima-schedule.json", name: "練馬区", city: "東京23区", areaCount: 128 },
  { slug: "edogawa", file: "edogawa-schedule.json", name: "江戸川区", city: "東京23区", areaCount: 154 },
  { slug: "suginami", file: "suginami-schedule.json", name: "杉並区", city: "東京23区", areaCount: 67 },
  { slug: "itabashi", file: "itabashi-schedule.json", name: "板橋区", city: "東京23区", areaCount: 134 },
  { slug: "shinjuku", file: "shinjuku-schedule.json", name: "新宿区", city: "東京23区", areaCount: 177 },
  { slug: "shibuya", file: "shibuya-schedule.json", name: "渋谷区", city: "東京23区", areaCount: 75 },
  { slug: "arakawa", file: "arakawa-schedule.json", name: "荒川区", city: "東京23区", areaCount: 76 },
  { slug: "toshima", file: "toshima-schedule.json", name: "豊島区", city: "東京23区", areaCount: 102 },
  { slug: "adachi", file: "adachi-schedule.json", name: "足立区", city: "東京23区", areaCount: 263 },
  { slug: "katsushika", file: "katsushika-schedule.json", name: "葛飾区", city: "東京23区", areaCount: 153 },
  { slug: "kita", file: "kita-schedule.json", name: "北区", city: "東京23区", areaCount: 114 },
  { slug: "sumida", file: "sumida-schedule.json", name: "墨田区", city: "東京23区", areaCount: 53 },
  { slug: "minato", file: "minato-schedule.json", name: "港区", city: "東京23区", areaCount: 121 },
  { slug: "nakano", file: "nakano-schedule.json", name: "中野区", city: "東京23区", areaCount: 71 },
  { slug: "chiyoda", file: "chiyoda-schedule.json", name: "千代田区", city: "東京23区", areaCount: 81 },
  { slug: "chiba-chuo", file: "chiba-chuo-schedule.json", name: "千葉市中央区", city: "千葉市", areaCount: 133 },
  { slug: "chiba-hanamigawa", file: "chiba-hanamigawa-schedule.json", name: "千葉市花見川区", city: "千葉市", areaCount: 76 },
  { slug: "chiba-inage", file: "chiba-inage-schedule.json", name: "千葉市稲毛区", city: "千葉市", areaCount: 65 },
  { slug: "chiba-wakaba", file: "chiba-wakaba-schedule.json", name: "千葉市若葉区", city: "千葉市", areaCount: 106 },
  { slug: "chiba-midori", file: "chiba-midori-schedule.json", name: "千葉市緑区", city: "千葉市", areaCount: 66 },
  { slug: "chiba-mihama", file: "chiba-mihama-schedule.json", name: "千葉市美浜区", city: "千葉市", areaCount: 41 },
  { slug: "kawasaki-kawasaki", file: "kawasaki-kawasaki-schedule.json", name: "川崎市川崎区", city: "川崎市", areaCount: 75 },
  { slug: "kawasaki-saiwai", file: "kawasaki-saiwai-schedule.json", name: "川崎市幸区", city: "川崎市", areaCount: 40 },
  { slug: "kawasaki-nakahara", file: "kawasaki-nakahara-schedule.json", name: "川崎市中原区", city: "川崎市", areaCount: 40 },
  { slug: "kawasaki-takatsu", file: "kawasaki-takatsu-schedule.json", name: "川崎市高津区", city: "川崎市", areaCount: 25 },
  { slug: "kawasaki-miyamae", file: "kawasaki-miyamae-schedule.json", name: "川崎市宮前区", city: "川崎市", areaCount: 27 },
  { slug: "kawasaki-tama", file: "kawasaki-tama-schedule.json", name: "川崎市多摩区", city: "川崎市", areaCount: 25 },
  { slug: "kawasaki-asao", file: "kawasaki-asao-schedule.json", name: "川崎市麻生区", city: "川崎市", areaCount: 28 },
  { slug: "osaka-miyakojima", file: "osaka-miyakojima-schedule.json", name: "大阪市都島区", city: "大阪市", areaCount: 47 },
  { slug: "osaka-fukushima", file: "osaka-fukushima-schedule.json", name: "大阪市福島区", city: "大阪市", areaCount: 40 },
  { slug: "osaka-konohana", file: "osaka-konohana-schedule.json", name: "大阪市此花区", city: "大阪市", areaCount: 47 },
  { slug: "osaka-nishi", file: "osaka-nishi-schedule.json", name: "大阪市西区", city: "大阪市", areaCount: 59 },
  { slug: "osaka-minato", file: "osaka-minato-schedule.json", name: "大阪市港区", city: "大阪市", areaCount: 53 },
  { slug: "osaka-taisho", file: "osaka-taisho-schedule.json", name: "大阪市大正区", city: "大阪市", areaCount: 45 },
  { slug: "osaka-tennoji", file: "osaka-tennoji-schedule.json", name: "大阪市天王寺区", city: "大阪市", areaCount: 70 },
  { slug: "osaka-naniwa", file: "osaka-naniwa-schedule.json", name: "大阪市浪速区", city: "大阪市", areaCount: 62 },
  { slug: "osaka-nishiyodogawa", file: "osaka-nishiyodogawa-schedule.json", name: "大阪市西淀川区", city: "大阪市", areaCount: 61 },
  { slug: "osaka-higashiyodogawa", file: "osaka-higashiyodogawa-schedule.json", name: "大阪市東淀川区", city: "大阪市", areaCount: 87 },
  { slug: "osaka-higashinari", file: "osaka-higashinari-schedule.json", name: "大阪市東成区", city: "大阪市", areaCount: 44 },
  { slug: "osaka-ikuno", file: "osaka-ikuno-schedule.json", name: "大阪市生野区", city: "大阪市", areaCount: 90 },
  { slug: "osaka-asahi", file: "osaka-asahi-schedule.json", name: "大阪市旭区", city: "大阪市", areaCount: 45 },
  { slug: "osaka-joto", file: "osaka-joto-schedule.json", name: "大阪市城東区", city: "大阪市", areaCount: 76 },
  { slug: "osaka-abeno", file: "osaka-abeno-schedule.json", name: "大阪市阿倍野区", city: "大阪市", areaCount: 68 },
  { slug: "osaka-sumiyoshi", file: "osaka-sumiyoshi-schedule.json", name: "大阪市住吉区", city: "大阪市", areaCount: 103 },
  { slug: "osaka-higashisumiyoshi", file: "osaka-higashisumiyoshi-schedule.json", name: "大阪市東住吉区", city: "大阪市", areaCount: 99 },
  { slug: "osaka-nishinari", file: "osaka-nishinari-schedule.json", name: "大阪市西成区", city: "大阪市", areaCount: 84 },
  { slug: "osaka-yodogawa", file: "osaka-yodogawa-schedule.json", name: "大阪市淀川区", city: "大阪市", areaCount: 88 },
  { slug: "osaka-tsurumi", file: "osaka-tsurumi-schedule.json", name: "大阪市鶴見区", city: "大阪市", areaCount: 57 },
  { slug: "osaka-suminoe", file: "osaka-suminoe-schedule.json", name: "大阪市住之江区", city: "大阪市", areaCount: 74 },
  { slug: "osaka-hirano", file: "osaka-hirano-schedule.json", name: "大阪市平野区", city: "大阪市", areaCount: 140 },
  { slug: "osaka-kita", file: "osaka-kita-schedule.json", name: "大阪市北区", city: "大阪市", areaCount: 107 },
  { slug: "osaka-chuo", file: "osaka-chuo-schedule.json", name: "大阪市中央区", city: "大阪市", areaCount: 174 },
  { slug: "yokohama-tsurumi", file: "yokohama-tsurumi-schedule.json", name: "横浜市鶴見区", city: "横浜市", areaCount: 133 },
  { slug: "yokohama-kanagawa", file: "yokohama-kanagawa-schedule.json", name: "横浜市神奈川区", city: "横浜市", areaCount: 152 },
  { slug: "yokohama-nishi", file: "yokohama-nishi-schedule.json", name: "横浜市西区", city: "横浜市", areaCount: 69 },
  { slug: "yokohama-naka", file: "yokohama-naka-schedule.json", name: "横浜市中区", city: "横浜市", areaCount: 228 },
  { slug: "yokohama-minami", file: "yokohama-minami-schedule.json", name: "横浜市南区", city: "横浜市", areaCount: 116 },
  { slug: "yokohama-hodogaya", file: "yokohama-hodogaya-schedule.json", name: "横浜市保土ケ谷区", city: "横浜市", areaCount: 77 },
  { slug: "yokohama-isogo", file: "yokohama-isogo-schedule.json", name: "横浜市磯子区", city: "横浜市", areaCount: 102 },
  { slug: "yokohama-kanazawa", file: "yokohama-kanazawa-schedule.json", name: "横浜市金沢区", city: "横浜市", areaCount: 97 },
  { slug: "yokohama-kohoku", file: "yokohama-kohoku-schedule.json", name: "横浜市港北区", city: "横浜市", areaCount: 111 },
  { slug: "yokohama-totsuka", file: "yokohama-totsuka-schedule.json", name: "横浜市戸塚区", city: "横浜市", areaCount: 55 },
  { slug: "yokohama-konan", file: "yokohama-konan-schedule.json", name: "横浜市港南区", city: "横浜市", areaCount: 84 },
  { slug: "yokohama-asahi", file: "yokohama-asahi-schedule.json", name: "横浜市旭区", city: "横浜市", areaCount: 83 },
  { slug: "yokohama-midori", file: "yokohama-midori-schedule.json", name: "横浜市緑区", city: "横浜市", areaCount: 66 },
  { slug: "yokohama-seya", file: "yokohama-seya-schedule.json", name: "横浜市瀬谷区", city: "横浜市", areaCount: 61 },
  { slug: "yokohama-sakae", file: "yokohama-sakae-schedule.json", name: "横浜市栄区", city: "横浜市", areaCount: 60 },
  { slug: "yokohama-izumi", file: "yokohama-izumi-schedule.json", name: "横浜市泉区", city: "横浜市", areaCount: 85 },
  { slug: "yokohama-aoba", file: "yokohama-aoba-schedule.json", name: "横浜市青葉区", city: "横浜市", areaCount: 79 },
  { slug: "yokohama-tsuzuki", file: "yokohama-tsuzuki-schedule.json", name: "横浜市都筑区", city: "横浜市", areaCount: 94 },
  { slug: "nagoya-chikusa", file: "nagoya-chikusa-schedule.json", name: "名古屋市千種区", city: "名古屋市", areaCount: 311 },
  { slug: "nagoya-higashi", file: "nagoya-higashi-schedule.json", name: "名古屋市東区", city: "名古屋市", areaCount: 86 },
  { slug: "nagoya-kita", file: "nagoya-kita-schedule.json", name: "名古屋市北区", city: "名古屋市", areaCount: 239 },
  { slug: "nagoya-nishi", file: "nagoya-nishi-schedule.json", name: "名古屋市西区", city: "名古屋市", areaCount: 184 },
  { slug: "nagoya-nakamura", file: "nagoya-nakamura-schedule.json", name: "名古屋市中村区", city: "名古屋市", areaCount: 372 },
  { slug: "nagoya-naka", file: "nagoya-naka-schedule.json", name: "名古屋市中区", city: "名古屋市", areaCount: 61 },
  { slug: "nagoya-showa", file: "nagoya-showa-schedule.json", name: "名古屋市昭和区", city: "名古屋市", areaCount: 200 },
  { slug: "nagoya-mizuho", file: "nagoya-mizuho-schedule.json", name: "名古屋市瑞穂区", city: "名古屋市", areaCount: 177 },
  { slug: "nagoya-atsuta", file: "nagoya-atsuta-schedule.json", name: "名古屋市熱田区", city: "名古屋市", areaCount: 89 },
  { slug: "nagoya-nakagawa", file: "nagoya-nakagawa-schedule.json", name: "名古屋市中川区", city: "名古屋市", areaCount: 510 },
  { slug: "nagoya-minato", file: "nagoya-minato-schedule.json", name: "名古屋市港区", city: "名古屋市", areaCount: 278 },
  { slug: "nagoya-minami", file: "nagoya-minami-schedule.json", name: "名古屋市南区", city: "名古屋市", areaCount: 351 },
  { slug: "nagoya-moriyama", file: "nagoya-moriyama-schedule.json", name: "名古屋市守山区", city: "名古屋市", areaCount: 170 },
  { slug: "nagoya-midori", file: "nagoya-midori-schedule.json", name: "名古屋市緑区", city: "名古屋市", areaCount: 214 },
  { slug: "nagoya-midori-odaka", file: "nagoya-midori-odaka-schedule.json", name: "名古屋市緑区（大高町地区）", city: "名古屋市", areaCount: 151 },
  { slug: "nagoya-midori-narumi", file: "nagoya-midori-narumi-schedule.json", name: "名古屋市緑区（鳴海町地区）", city: "名古屋市", areaCount: 84 },
  { slug: "nagoya-meito", file: "nagoya-meito-schedule.json", name: "名古屋市名東区", city: "名古屋市", areaCount: 172 },
  { slug: "nagoya-tempaku", file: "nagoya-tempaku-schedule.json", name: "名古屋市天白区", city: "名古屋市", areaCount: 140 },
];

export const MUNI_REGISTRY_TOTAL_AREAS = 10721;
